language: ruby

sudo: required

services:
  - docker

before_install:
  - echo "Installing test gems then the azure cli"
  - gem install jsonlint
  - sudo apt-get install jq
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
  - az login `echo $AZURE_TRAVIS_SERVICE_CREDENTIALS | base64 -d`

  
install: true

script:
  - jsonlint nestedtemplates/*
  - UNIQUEID="$(date +%s)"
  - TESTRESOURCEGROUPNAME="TravisTestResourceGroup${UNIQUEID}"
  - export ADMINPASSWORD=TravisAdminpwd1234!
  - sed -i "s@ARTIFACTSLOCATION@$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH@g" ci/azuredeploy.parameters.json
  - sed -i "s@UNIQUEID@$UNIQUEID@g" ci/azuredeploy.parameters.json
  - sed -i "s@solace/solace-pubsub-standard:latest@${SOLACE_DOCKER_URL_PARAMETER_VALUE}@g" ci/azuredeploy.parameters.json
  - sed -i "s@ADMINPASSWORD@$ADMINPASSWORD@g" ci/azuredeploy.parameters.json
  - az group create --name $TESTRESOURCEGROUPNAME --location "centralus"
  - echo "Creating cluster and waiting to become active"
  - "travis_wait 30 sleep 1800 &"
  - az group deployment create --name TravisTestDeployment${UNIQUEID} --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
  - az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
  - ########################################
  - #exit
  - ########################################
  - export url=`az network public-ip show --resource-group $TESTRESOURCEGROUPNAME --name myLBPublicIPD --query [ipAddress] --output tsv`; echo $url
  - curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
  - tar -xvf SDKPERF_C_LINUX64
  - pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
  - sleep 30
  - bash -c 'if [[ -z `curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi'
  - curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><redundancy></redundancy></show></rpc>"
  - curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>"
  

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "JSON linted"
  - echo "Cluster deployment tested"
  - echo "Messaging tested"

after_script:
  - az group delete --name $TESTRESOURCEGROUPNAME --yes

